{% set name = "odc-geo" %}
{% set version = "0.1.1rc0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6fc15857d4c6a84bbc6de968f7eea3e4969ab3f3051de514770f48ce7c0467e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - shapely
    - pyproj
    - affine
    - numpy
    - cachetools
    - xarray >=0.19

test:
  imports:
    - odc.geo
    - odc.geo.xr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-geo/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://odc-geo.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-geo/
  summary: Geometry Classes and Operations (opendatacube)

  description: |
    This library combines geometry shape classes from `shapely` with CRS from
    `pyproj` to provide a number of data types and utilities useful for working
    with geospatial metadata and geo-registered `xarray` rasters.

extra:
  recipe-maintainers:
    - kirill888
