{% set name = "odc-geo" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 2dfcf085b8baac5ca57977cca73e2e357b0c287a37b30d88191a1bc027c916bb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - shapely
    - pyproj >=3.0.0
    - affine
    - numpy
    - cachetools
    - xarray >=0.19

test:
  imports:
    - odc.geo
    - odc.geo.xr
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-geo/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://odc-geo.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-geo/
  summary: Geometry Classes and Operations (opendatacube)

  description: |
    This library combines geometry shape classes from `shapely` with CRS from
    `pyproj` to provide a number of data types and utilities useful for working
    with geospatial metadata and geo-registered `xarray` rasters.

extra:
  recipe-maintainers:
    - kirill888
