{% set name = "odc-geo" %}
{% set version = "0.5.0rc1" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cd42432a642219f5c7150a60914daea4b8de830cff7c7f7a89c4081180f9ca40 

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=0.3.2,<4
    - pip
  run:
    - python >={{ python_min }}
    - shapely
    - pyproj >=3.0.0
    - affine
    - numpy
    - cachetools
    - xarray >=0.19

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - odc.geo
    - odc.geo.xr
  commands:
    - pip check

about:
  home: https://github.com/opendatacube/odc-geo/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  doc_url: https://odc-geo.readthedocs.io/
  dev_url: https://github.com/opendatacube/odc-geo/
  summary: Geometry Classes and Operations (opendatacube)

  description: |
    This library combines geometry shape classes from `shapely` with CRS from
    `pyproj` to provide a number of data types and utilities useful for working
    with geospatial metadata and geo-registered `xarray` rasters.

extra:
  recipe-maintainers:
    - kirill888
